# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: BMCTTAutoRun@1
  inputs:
    HCIConnection: 'CW06:16196'
    UserID: 'amimee0'
    Password: 'syc4567'
    TestLocationPath: 'C:\Users\meastman\Compuware\Workbench\workspace\CWXTCOB\Tests\Scenarios'
    CLIInstallationPath: 'C:\WorkbenchCLI'
    Configuration: 'LocalTTTConf'
    LocalTTTConfiguration: 'C:\Users\meastman\Compuware\Workbench\workspace\TotalTestConfiguration'